default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: format-check
        name: Check formatting
        entry: pnpm exec prettier --check .
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: eslint
        name: ESLint
        entry: pnpm lint
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: commitlint
        name: Commit message lint
        entry: pnpm exec commitlint --edit
        language: system
        stages: [commit-msg]
